// This file is auto-generated by `npx convex dev`.
// Do not edit manually. Run `npx convex codegen` to regenerate.

export const api = {
  users: {
    getUser: "users:getUser" as any,
    getUserByEmail: "users:getUserByEmail" as any,
    createOrUpdateUser: "users:createOrUpdateUser" as any,
  },
  analytics: {
    trackEvent: "analytics:trackEvent" as any,
    getRecentEvents: "analytics:getRecentEvents" as any,
    getEventsByType: "analytics:getEventsByType" as any,
    getTopProducts: "analytics:getTopProducts" as any,
    getDashboardStats: "analytics:getDashboardStats" as any,
  },
  inventory: {
    getStockLevel: "inventory:getStockLevel" as any,
    getStockLevelByVariant: "inventory:getStockLevelByVariant" as any,
    updateStock: "inventory:updateStock" as any,
    getAllStock: "inventory:getAllStock" as any,
  },
  wishlist: {
    getWishlist: "wishlist:getWishlist" as any,
    isInWishlist: "wishlist:isInWishlist" as any,
    addToWishlist: "wishlist:addToWishlist" as any,
    removeFromWishlist: "wishlist:removeFromWishlist" as any,
  },
  notifications: {
    getNotifications: "notifications:getNotifications" as any,
    getUnreadCount: "notifications:getUnreadCount" as any,
    createNotification: "notifications:createNotification" as any,
    markAsRead: "notifications:markAsRead" as any,
    markAllAsRead: "notifications:markAllAsRead" as any,
  },
  webhooks: {
    recordStripeEvent: "webhooks:recordStripeEvent" as any,
  },
};
