// This file is auto-generated by `npx convex dev`.
// Do not edit manually. Run `npx convex codegen` to regenerate.

import type {
  FunctionReference,
  RegisteredFunction,
} from "convex/server";

export type ReferenceOrString = FunctionReference<string, any, any, any> | string;

export type DataModel = any;

export type FunctionReturnType<T extends RegisteredFunction<any, any>> =
  T extends RegisteredFunction<any, infer R> ? R : never;
